name: nflproj
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - duckdb
  - scikit-learn
  - matplotlib
  - jupyterlab
  - xgboost
  - pip
  - pip:
      - nfl_data_py
prefix: /opt/anaconda3/envs/nflproj
